{
    'name': 'Thames Configuration',
    'version': '1.0',
    'summary': 'Installs all necessary Thames CC modules.',
    'category': 'Administration',
    'author': 'Thames CC',
    'website': 'https://www.thamescc.com',
    'depends': [
        'crm',
        'sale_management',
        'stock',
        'website',
        'account',
        'thames_crm_customizations',
    ],
    'data': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
